name: Testing App
on: push
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package.json')}}
      - name: Install dependencies
        run: yarn install
      - name: Lint application
        run: yarn run lint
      - name: Build application
        run: yarn run build